// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class GameSession
{
    public int Id { get; set; }

    public int QuizId { get; set; }

    public int HostId { get; set; }

    public string PinCode { get; set; }

    public string GameType { get; set; }

    public string Status { get; set; }

    public int MinPlayer { get; set; }

    public int MaxPlayer { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? EndedAt { get; set; }

    public virtual User Host { get; set; }

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    public virtual Quiz Quiz { get; set; }
}