// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class GroupMember
{
    public int GroupId { get; set; }

    public int PlayerId { get; set; }

    public int Rank { get; set; }

    public int TotalScore { get; set; }

    public DateTime JoinedAt { get; set; }

    public string Status { get; set; }

    public virtual Group Group { get; set; }

    public virtual Player Player { get; set; }

 
}