// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int Rank { get; set; }

    public int MaxMembers { get; set; }

    public int TotalPoint { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();
}