// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Player
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Nickname { get; set; }

    public int PlayerCode { get; set; }

    public string AvatarUrl { get; set; }

    public int Score { get; set; }

    public int? SessionId { get; set; }

    public virtual ICollection<PlayerAnswer> PlayerAnswers { get; set; } = new List<PlayerAnswer>();

    public virtual GameSession Session { get; set; }

    public virtual User User { get; set; }
}