// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Question
{
    public int Id { get; set; }

    public int QuizId { get; set; }

    public string Text { get; set; }

    public string Type { get; set; }

    public string OptionA { get; set; }

    public string OptionB { get; set; }

    public string OptionC { get; set; }

    public string OptionD { get; set; }

    public string IsCorrect { get; set; }

    public int Score { get; set; }

    public bool Flag { get; set; }

    public int? TimeLimit { get; set; }

    public int? Arrange { get; set; }

    public virtual ICollection<PlayerAnswer> PlayerAnswers { get; set; } = new List<PlayerAnswer>();

    public virtual Quiz Quiz { get; set; }
}