// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Quiz
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int QuizCode { get; set; }

    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public int CategoryId { get; set; }

    public bool IsPublic { get; set; }

    public string ThumbnailUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Category Category { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GameSession> GameSessions { get; set; } = new List<GameSession>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}