// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class Quiz
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int QuizCode { get; set; }

    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public int CategoryId { get; set; }

    public bool IsPublic { get; set; }

    public string ThumbnailUrl { get; set; }

    public DateTime CreatedAt { get; set; }
    [Required]

    public int? MaxPlayer { get; set; }
    [Required]
    public int? MinPlayer { get; set; }

    public bool? Favorite { get; set; }

    public string GameMode { get; set; }

    public int NumberOfJoinedPlayers { get; set; } = 0; // default value = 0

    public virtual Category Category { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}