// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class UserServicePack
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ServicePackId { get; set; }

    public DateTime ActivatedAt { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ServicePack ServicePack { get; set; }

    public virtual User User { get; set; }
}